#version: '3.9'

services:
 
  warp_api:
    build:
      context: ./
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./server
    ports:
      - "8888:8888"
